In [1]:
import pickle as pkl

In [2]:
data = pkl.load(open("/srv/scratch/anusri/chrombpnet_paper/tobias_scripts/GM12878/actual_tobias_files/GM12878.atac.filt.merged_AtacBias.pickle", "rb"))




In [5]:
print(data)
import numpy as np
tobias_atac_pssm_forward=np.expand_dims(np.transpose(data.bias['forward'].pssm[0:4])[:,[0,2,3,1]],axis=-1)




In [14]:
from scipy.special import softmax
print(softmax(tobias_atac_pssm_forward.reshape(25,4),axis=1))








[[0.24282416 0.24226894 0.26966318 0.24524371]
 [0.20928797 0.26398114 0.26736289 0.259368  ]
 [0.17446342 0.28367319 0.26494466 0.27691873]
 [0.22525632 0.21662879 0.39530636 0.16280852]
 [0.18287636 0.38674447 0.27413136 0.15624781]
 [0.29412396 0.21208794 0.27052872 0.22325939]
 [0.14020627 0.49420271 0.20903911 0.15655192]
 [0.38920416 0.12461989 0.20613727 0.28003867]
 [0.13969722 0.27117099 0.52977444 0.05935736]
 [0.16054587 0.31427484 0.1819562  0.34322309]
 [0.1774914  0.35536563 0.20405205 0.26309093]
 [0.10811996 0.43571461 0.12494991 0.33121552]
 [0.35965768 0.14517232 0.14313966 0.35203033]
 [0.326043   0.13135149 0.42964352 0.11296199]
 [0.26714949 0.20456622 0.35838665 0.16989764]
 [0.32943261 0.20149536 0.31143285 0.15763918]
 [0.09236194 0.49319822 0.25941491 0.15502494]
 [0.25191494 0.24409702 0.15920359 0.34478445]
 [0.17753849 0.22166341 0.44103977 0.15975832]
 [0.22597862 0.26695645 0.22560547 0.28145946]
 [0.16268945 0.27752231 0.36668153 0.19310671]
 [0.17027241 