In [1]:
import tensorflow as tf
from tensorflow.keras.utils import get_custom_objects
custom_objects={"tf":tf}  
get_custom_objects().update(custom_objects)

In [2]:
gm_fold1_bias_model = tf.keras.models.load_model("/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/chrombpnet/folds/ATAC/GM12878/GM12878_07.08.2022_bias_128_4_1234_0.4_fold_1_data_type_ATAC_PE/chrombpnet_model/bias_model_scaled.h5",
                                compile=False)
gm_fold1_cbp_w_bias_model = tf.keras.models.load_model("/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/chrombpnet/folds/ATAC/GM12878/GM12878_07.08.2022_bias_128_4_1234_0.4_fold_1_data_type_ATAC_PE/chrombpnet_model/chrombpnet.h5",
                                compile=False)
gm_fold1_cbp_wo_bias_model = tf.keras.models.load_model("/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/chrombpnet/folds/ATAC/GM12878/GM12878_07.08.2022_bias_128_4_1234_0.4_fold_1_data_type_ATAC_PE/chrombpnet_model/chrombpnet_wo_bias.h5",
                                compile=False)

/users/anusri/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/layers/core.py:1059: UserWarning:  is not loaded, but a Lambda layer uses it. It may cause errors.
  , UserWarning)


ResourceExhaustedError: OOM when allocating tensor with shape[3,512,512] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [Op:Add]

In [2]:
import tensorflow as tf
from tensorflow.keras.utils import get_custom_objects
from tensorflow.keras.models import load_model
import numpy as np
custom_objects={"tf": tf}
get_custom_objects().update(custom_objects)
inputs = np.zeros((12,2114,4))

In [3]:
model_in_h5_format="/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/chrombpnet/folds/ATAC/GM12878/GM12878_07.14.2022_bias_128_4_1234_0.4_fold_3_data_type_ATAC_PE/chrombpnet_model/chrombpnet.h5"
model=load_model(model_in_h5_format,compile=False)
outputs = model(inputs)

/users/anusri/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/layers/core.py:1059: UserWarning:  is not loaded, but a Lambda layer uses it. It may cause errors.
  , UserWarning)


In [4]:
model_dir_untared="/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/DNASE/ENCSR791BHE/chrombpnet_model_encsr880cub_bias/new_chrombpnet_model/chrombpnet_new/"
modelf = tf.saved_model.load(model_dir_untared)

In [12]:
output = modelf.signatures['serving_default'](**{'sequence':inputs.astype('float32')})


In [16]:
outputs[0].shape

TensorShape([12, 1000])

In [17]:
outputs[1].shape

TensorShape([12, 1])

In [18]:
output

{'logcount_predictions': <tf.Tensor: shape=(12, 1), dtype=float32, numpy=
 array([[2.4863787],
        [2.4863787],
        [2.4863787],
        [2.4863787],
        [2.4863787],
        [2.4863787],
        [2.4863787],
        [2.4863787],
        [2.4863787],
        [2.4863787],
        [2.4863787],
        [2.4863787]], dtype=float32)>,
 'logits_profile_predictions': <tf.Tensor: shape=(12, 1000), dtype=float32, numpy=
 array([[7.0896025, 7.0896025, 7.0896025, ..., 7.0896025, 7.0896025,
         7.0896025],
        [7.0896025, 7.0896025, 7.0896025, ..., 7.0896025, 7.0896025,
         7.0896025],
        [7.0896025, 7.0896025, 7.0896025, ..., 7.0896025, 7.0896025,
         7.0896025],
        ...,
        [7.0896025, 7.0896025, 7.0896025, ..., 7.0896025, 7.0896025,
         7.0896025],
        [7.0896025, 7.0896025, 7.0896025, ..., 7.0896025, 7.0896025,
         7.0896025],
        [7.0896025, 7.0896025, 7.0896025, ..., 7.0896025, 7.0896025,
         7.0896025]], dtype=float32)>}

In [21]:
outputs

[<tf.Tensor: shape=(12, 1000), dtype=float32, numpy=
 array([[33.387974, 33.387974, 33.387974, ..., 33.387974, 33.387974,
         33.387974],
        [33.387974, 33.387974, 33.387974, ..., 33.387974, 33.387974,
         33.387974],
        [33.387974, 33.387974, 33.387974, ..., 33.387974, 33.387974,
         33.387974],
        ...,
        [33.387974, 33.387974, 33.387974, ..., 33.387974, 33.387974,
         33.387974],
        [33.387974, 33.387974, 33.387974, ..., 33.387974, 33.387974,
         33.387974],
        [33.387974, 33.387974, 33.387974, ..., 33.387974, 33.387974,
         33.387974]], dtype=float32)>,
 <tf.Tensor: shape=(12, 1), dtype=float32, numpy=
 array([[3.8139498],
        [3.8139498],
        [3.8139498],
        [3.8139498],
        [3.8139498],
        [3.8139498],
        [3.8139498],
        [3.8139498],
        [3.8139498],
        [3.8139498],
        [3.8139498],
        [3.8139498]], dtype=float32)>]

In [25]:
def softmax(x, temp=1):
    norm_x = x - np.mean(x,axis=1, keepdims=True)
    return np.exp(temp*norm_x)/np.sum(np.exp(temp*norm_x), axis=1, keepdims=True)


KeyError: 0

In [42]:
allt1 = softmax(outputs[0]) * (np.expand_dims(np.exp(outputs[1])[:,0],axis=1))

In [33]:
(np.expand_dims(np.exp(outputs[1])[:,0],axis=1)).shape

(12, 1)

In [36]:
np.exp(outputs[1])[:,0]

(12,)

In [37]:
allt = softmax(outputs[0]) * (np.expand_dims(np.exp(outputs[1])[:,0],axis=1))

In [39]:
allt = softmax(outputs[0]) * np.exp(outputs[1])

In [41]:
allt

array([[0.04532913, 0.04532913, 0.04532913, ..., 0.04532913, 0.04532913,
        0.04532913],
       [0.04532913, 0.04532913, 0.04532913, ..., 0.04532913, 0.04532913,
        0.04532913],
       [0.04532913, 0.04532913, 0.04532913, ..., 0.04532913, 0.04532913,
        0.04532913],
       ...,
       [0.04532913, 0.04532913, 0.04532913, ..., 0.04532913, 0.04532913,
        0.04532913],
       [0.04532913, 0.04532913, 0.04532913, ..., 0.04532913, 0.04532913,
        0.04532913],
       [0.04532913, 0.04532913, 0.04532913, ..., 0.04532913, 0.04532913,
        0.04532913]], dtype=float32)

In [43]:
allt1

array([[0.04532913, 0.04532913, 0.04532913, ..., 0.04532913, 0.04532913,
        0.04532913],
       [0.04532913, 0.04532913, 0.04532913, ..., 0.04532913, 0.04532913,
        0.04532913],
       [0.04532913, 0.04532913, 0.04532913, ..., 0.04532913, 0.04532913,
        0.04532913],
       ...,
       [0.04532913, 0.04532913, 0.04532913, ..., 0.04532913, 0.04532913,
        0.04532913],
       [0.04532913, 0.04532913, 0.04532913, ..., 0.04532913, 0.04532913,
        0.04532913],
       [0.04532913, 0.04532913, 0.04532913, ..., 0.04532913, 0.04532913,
        0.04532913]], dtype=float32)

In [46]:
output
allt = softmax(output["logits_profile_predictions"]) * np.exp(output["logcount_predictions"])